ws.port: 5051
server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M
project:
  folder: E:/webser/easychat/

log:
  root:
    level: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easychat
    password: Yy002916
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  web:
    resources:
      add-mappings: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000

admin:
  emails: test@qq.com
dev: false